[workspace]
channels = ["conda-forge"]
name = "compress-sat"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
earthengine-api = ">=1.7.29,<2"
pandas = ">=3.0.3,<4"
pytest = ">=9.0.3,<10"
